"""add vacation_start_end to coaches

Revision ID: 07dfca3a3f88
Revises: aff04e922116
Create Date: 2026-06-18 16:37:44.265889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07dfca3a3f88'
down_revision: Union[str, Sequence[str], None] = 'aff04e922116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('vacation_start', sa.Date(), nullable=True))
    op.add_column('coaches', sa.Column('vacation_end', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coaches', 'vacation_end')
    op.drop_column('coaches', 'vacation_start')
    # ### end Alembic commands ###
