"""add coach_vacations table

Revision ID: 69889c273334
Revises: 07dfca3a3f88
Create Date: 2026-06-18 16:42:36.794822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69889c273334'
down_revision: Union[str, Sequence[str], None] = '07dfca3a3f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_vacations',
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('coaches', 'vacation_start')
    op.drop_column('coaches', 'vacation_end')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('vacation_end', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('coaches', sa.Column('vacation_start', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_table('coach_vacations')
    # ### end Alembic commands ###
