/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingsRouteImport } from './routes/trainings'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as CommissionRouteImport } from './routes/commission'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AthletesRouteImport } from './routes/athletes'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsNewRouteImport } from './routes/reports/new'
import { Route as PlansNewRouteImport } from './routes/plans/new'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminProgramsRouteImport } from './routes/admin/programs'
import { Route as AdminOrgRouteImport } from './routes/admin/org'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'

const TrainingsRoute = TrainingsRouteImport.update({
  id: '/trainings',
  path: '/trainings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionRoute = CommissionRouteImport.update({
  id: '/commission',
  path: '/commission',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesRoute = AthletesRouteImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsNewRoute = ReportsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ReportsRoute,
} as any)
const PlansNewRoute = PlansNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PlansRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/admin/programs',
  path: '/admin/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrgRoute = AdminOrgRouteImport.update({
  id: '/admin/org',
  path: '/admin/org',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/athletes': typeof AthletesRoute
  '/attendance': typeof AttendanceRoute
  '/coaches': typeof CoachesRoute
  '/commission': typeof CommissionRoute
  '/competitions': typeof CompetitionsRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRouteWithChildren
  '/schedules': typeof SchedulesRoute
  '/trainings': typeof TrainingsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/org': typeof AdminOrgRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/users': typeof AdminUsersRoute
  '/plans/new': typeof PlansNewRoute
  '/reports/new': typeof ReportsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/athletes': typeof AthletesRoute
  '/attendance': typeof AttendanceRoute
  '/coaches': typeof CoachesRoute
  '/commission': typeof CommissionRoute
  '/competitions': typeof CompetitionsRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRouteWithChildren
  '/schedules': typeof SchedulesRoute
  '/trainings': typeof TrainingsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/org': typeof AdminOrgRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/users': typeof AdminUsersRoute
  '/plans/new': typeof PlansNewRoute
  '/reports/new': typeof ReportsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/athletes': typeof AthletesRoute
  '/attendance': typeof AttendanceRoute
  '/coaches': typeof CoachesRoute
  '/commission': typeof CommissionRoute
  '/competitions': typeof CompetitionsRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRouteWithChildren
  '/schedules': typeof SchedulesRoute
  '/trainings': typeof TrainingsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/org': typeof AdminOrgRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/users': typeof AdminUsersRoute
  '/plans/new': typeof PlansNewRoute
  '/reports/new': typeof ReportsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/athletes'
    | '/attendance'
    | '/coaches'
    | '/commission'
    | '/competitions'
    | '/groups'
    | '/login'
    | '/plans'
    | '/profile'
    | '/reports'
    | '/schedules'
    | '/trainings'
    | '/admin/audit'
    | '/admin/org'
    | '/admin/programs'
    | '/admin/users'
    | '/plans/new'
    | '/reports/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/athletes'
    | '/attendance'
    | '/coaches'
    | '/commission'
    | '/competitions'
    | '/groups'
    | '/login'
    | '/plans'
    | '/profile'
    | '/reports'
    | '/schedules'
    | '/trainings'
    | '/admin/audit'
    | '/admin/org'
    | '/admin/programs'
    | '/admin/users'
    | '/plans/new'
    | '/reports/new'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/athletes'
    | '/attendance'
    | '/coaches'
    | '/commission'
    | '/competitions'
    | '/groups'
    | '/login'
    | '/plans'
    | '/profile'
    | '/reports'
    | '/schedules'
    | '/trainings'
    | '/admin/audit'
    | '/admin/org'
    | '/admin/programs'
    | '/admin/users'
    | '/plans/new'
    | '/reports/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AthletesRoute: typeof AthletesRoute
  AttendanceRoute: typeof AttendanceRoute
  CoachesRoute: typeof CoachesRoute
  CommissionRoute: typeof CommissionRoute
  CompetitionsRoute: typeof CompetitionsRoute
  GroupsRoute: typeof GroupsRoute
  LoginRoute: typeof LoginRoute
  PlansRoute: typeof PlansRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  SchedulesRoute: typeof SchedulesRoute
  TrainingsRoute: typeof TrainingsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminOrgRoute: typeof AdminOrgRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainings': {
      id: '/trainings'
      path: '/trainings'
      fullPath: '/trainings'
      preLoaderRoute: typeof TrainingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commission': {
      id: '/commission'
      path: '/commission'
      fullPath: '/commission'
      preLoaderRoute: typeof CommissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes': {
      id: '/athletes'
      path: '/athletes'
      fullPath: '/athletes'
      preLoaderRoute: typeof AthletesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/new': {
      id: '/reports/new'
      path: '/new'
      fullPath: '/reports/new'
      preLoaderRoute: typeof ReportsNewRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/plans/new': {
      id: '/plans/new'
      path: '/new'
      fullPath: '/plans/new'
      preLoaderRoute: typeof PlansNewRouteImport
      parentRoute: typeof PlansRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/admin/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/org': {
      id: '/admin/org'
      path: '/admin/org'
      fullPath: '/admin/org'
      preLoaderRoute: typeof AdminOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlansRouteChildren {
  PlansNewRoute: typeof PlansNewRoute
}

const PlansRouteChildren: PlansRouteChildren = {
  PlansNewRoute: PlansNewRoute,
}

const PlansRouteWithChildren = PlansRoute._addFileChildren(PlansRouteChildren)

interface ReportsRouteChildren {
  ReportsNewRoute: typeof ReportsNewRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsNewRoute: ReportsNewRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AthletesRoute: AthletesRoute,
  AttendanceRoute: AttendanceRoute,
  CoachesRoute: CoachesRoute,
  CommissionRoute: CommissionRoute,
  CompetitionsRoute: CompetitionsRoute,
  GroupsRoute: GroupsRoute,
  LoginRoute: LoginRoute,
  PlansRoute: PlansRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRouteWithChildren,
  SchedulesRoute: SchedulesRoute,
  TrainingsRoute: TrainingsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminOrgRoute: AdminOrgRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminUsersRoute: AdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
